### ISSUE TITLE
How to access the database?

### ISSUE THREAD

**Issue by hy-chen** [mustilica/tt-history#3]
Hi there! Thanks for your awesome project. I'm a student researcher working on the NLP project at UofT. I'm wondering if I can use your collected data to do some analysis. Only data from Nov 2019 - Present is needed. The 10-minute granularity really makes this database unique and very useful to my analysis. Thanks!

(Fast response will be greatly appreciated as the project duration is short. )

**Comment by ilhan-mstf** [comment]
Hi,
I can provide it to you at night.

**Comment by ilhan-mstf** [comment]
@hy-chen Can you send an email to ilhan.mstf@gmail.com
